name: Install pip dependencies
description: Install pip dependencies
runs:
  using: composite
  steps:
    - uses: action/checkout@v4
    - uses: ./.github/actions/checkout-python-greetings
    - name: Install dependencies
      working-directory: 'python-greetings'
      run: |
        pip install -r requirements.txt
      shell: bash

