name: Test on environment
description: Test on environment
inputs:
  GITHUB_ENVIRONMENT:
    description: The environment to deploy to
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/checkout-course-js-api-framework
    - name: Run tests on environment
      working-directory: 'course-js-api-framework'
      run: |
        npm install
        npm run greetings greetings_${{ inputs.GITHUB_ENVIRONMENT }}
      shell: bash
