name: Deploy to environment
description: Deploy to environment
inputs:
  GITHUB_ENVIRONMENT:
    description: The environment to deploy to
    required: true
  PORT:
    description: The port to use
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/checkout-python-greetings
    - name: Deploy to environment
      working-directory: 'python-greetings'
      run: |
        pm2 delete greetings-app-${{ inputs.GITHUB_ENVIRONMENT }} || true
        pm2 start app.py --name greetings-app-${{ inputs.GITHUB_ENVIRONMENT }} -- --port ${{ inputs.PORT }}
      shell: bash
